## Programming Assignment 2: Lexical Scoping
## Caching the Inverse of a Matrix
## The pair of functions are used to create a special object that stores the matrix and caches its inverse

makeCacheMatrix <- function(x = matrix()) {
  ## This function provides a unique "matrix" that can be used to cache the inverse.
  set <- function(y) {
    x <<- y
    any <<- NULL
    
  }
  get <- function() x
  setInverse <- function(inverse) any <<- inverse
  getInverse <- function() any
  list(set = set, get = get,
       setInverse = setInverse,
       getInverse = getInverse)
  }

cacheSolve <- function(x, ...) {
        ## This function computes the inverse of the matrix generated by the makeCacheMatrix
        ## If the inverse has already been computed and the matrix has not changed,
        ## then cachesolve must recover the inverse from the cache.
  n <- x$getInverse()
  if(!is.null(n)) {
    message("gaining cached data")
    return(n)
  }
  q <- x$getInverse()
  n <- solve(q, ...)
  x$setInverse(n)
  n
}
